language: R
sudo: false
cache: packages

r:
- 3.5
- 3.6
- oldrel
- release
- devel

r_build_args: --no-multiarch
r_check_args: --as-cran --run-donttest

warnings_are_errors: false


before_install:
  - sudo $(which R) CMD javareconf